SurveyMVC/Controllers/ResponsesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SurveyApp.DataTransferObject.Requests.Response;
using SurveyApp.Services;
using SurveyMVC.Models;
using System.Data;
using System.Reflection.Metadata;

namespace SurveyMVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ResponsesController : Controller
    {
        private readonly IResponseService responseService;
        private readonly ISurveyService surveyService;
        private readonly IQuestionService questionService;
        public ResponsesController(IResponseService responseService, ISurveyService surveyService, IQuestionService questionService)
        {
            this.responseService = responseService;
            this.surveyService = surveyService;
            this.questionService = questionService; 
        }

        public async Task<IActionResult> Index(int surveyId = 1)
        {
            var responses = await responseService.GetAllResponsesBySurveyIdAsync(surveyId);
            var survey = await surveyService.GetSurveyAsync(surveyId);
            var responseViewModel = new ResponsesViewModel
            {
                Responses = responses,
                Survey = survey
            };
            return View(responseViewModel);
        }

        public async Task<IActionResult> Graphic(int surveyId = 1)
        {
            var responses = await responseService.GetAllResponsesBySurveyIdAsync(surveyId);
            var survey = await surveyService.GetSurveyAsync(surveyId);
            var questions = await questionService.GetAllQuestionsBySurveyIdAsync(surveyId);
            var graphicViewModel = new GraphicViewModel
            {
                Questions = questions,
                Responses = responses,
                Survey = survey
            };
            return View(graphicViewModel);

        }


        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Submit([FromBody] CreateNewResponseRequest request)
        {
            if (ModelState.IsValid)
            {
                await responseService.CreateResponseAsync(request);
                return Json(request);
            }
            return BadRequest(ModelState.Keys.SelectMany(key => ModelState[key].Errors));

        }
    }
}

SurveyMVC/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using SurveyApp.Services;
using SurveyMVC.Models;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;

namespace SurveyMVC.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserService service;

        public UsersController(IUserService service)
        {
            this.service = service;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Login(UserLoginViewModel userLogin)
        {
            if (ModelState.IsValid)
            {
                var user = await service.ValidateUserAsync(userLogin.UserName, userLogin.Password);
                if (user != null)
                {
                    Claim[] claims = new Claim[]
                    {
                        new Claim(JwtRegisteredClaimNames.UniqueName, user.Name),
                        new Claim(ClaimTypes.Email, user.Email),
                        new Claim(ClaimTypes.Role, user.Role)
                    };

                    var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("SurveySecretWord"));
                    var credential = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);
                    var token = new JwtSecurityToken(
                        issuer: "server",
                        audience: "client",
                        claims: claims,
                        notBefore: DateTime.Now,
                        expires: DateTime.Now.AddDays(1),
                        signingCredentials: credential
                    );
                    var generatedToken = new JwtSecurityTokenHandler().WriteToken(token);
                    if (generatedToken != null)
                    {
                        HttpContext.Session.SetString("JWTToken", generatedToken);
                    }
                    return RedirectToAction("Index", "Home", new {token = generatedToken});
                }
                ModelState.AddModelError("login", "Username or password is wrong");
            }
            return View();
        }

        public IActionResult Logoff()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

SurveyMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SurveyMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SurveyMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SurveyMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Responses" asp-action="Index">Responses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Logoff">Logoff</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Log In</a>
                            </li>        
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SurveyMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>